### ISSUE TITLE
希望土豆丝1可以更新支持最新的加密和混淆

### ISSUE THREAD

**Issue by zhchan** [Potatso/Potatso-Management#1]
### 问题描述
土豆丝1好久没更新啦。

### 期望结果
更新一下1代可怜一下iOS9用户咯。

**Comment by icodesign** [comment]
暂时先不考虑。目前主要精力在 2 上。

**Comment by zhchan** [comment]
嗷， 谢谢大佬

2016年10月31日星期一，Lei Wang <notifications@github.com> 写道：
